"""empty message

Revision ID: 0b13c19e2a3d
Revises: 474365d232dd
Create Date: 2026-03-10 11:53:43.425980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b13c19e2a3d'
down_revision: Union[str, Sequence[str], None] = '474365d232dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Credentials',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('access_key', sa.String(length=512), nullable=True),
    sa.Column('refresh_key', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Credentials_user_id'), 'Credentials', ['user_id'], unique=True)
    op.create_table('Principal',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('principal', sa.String(length=128), nullable=False),
    sa.Column('password_hashed', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Principal_principal'), 'Principal', ['principal'], unique=True)
    op.create_index(op.f('ix_Principal_user_id'), 'Principal', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Principal_user_id'), table_name='Principal')
    op.drop_index(op.f('ix_Principal_principal'), table_name='Principal')
    op.drop_table('Principal')
    op.drop_index(op.f('ix_Credentials_user_id'), table_name='Credentials')
    op.drop_table('Credentials')
    # ### end Alembic commands ###
