"""empty message

Revision ID: 50863a78ad7b
Revises: 80d9e44bc257
Create Date: 2026-03-12 18:13:58.923564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '50863a78ad7b'
down_revision: Union[str, Sequence[str], None] = '80d9e44bc257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Note',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=26), nullable=False),
    sa.Column('updated_by', sa.String(length=26), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tag',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.alter_column('Principal', 'role',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('User', 'role',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'role',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('Principal', 'role',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.drop_table('Tag')
    op.drop_table('Note')
    # ### end Alembic commands ###
