"""empty message

Revision ID: 5e9c58528e81
Revises: 9c424d825f9b
Create Date: 2026-02-10 17:09:07.172633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5e9c58528e81'
down_revision: Union[str, Sequence[str], None] = '9c424d825f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('username', sa.String(length=32), nullable=False))
    op.drop_column('User', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('name', mysql.VARCHAR(length=32), nullable=False))
    op.drop_column('User', 'username')
    # ### end Alembic commands ###
