"""add default role

Revision ID: 80d9e44bc257
Revises: ce85248a2853
Create Date: 2026-03-10 22:32:00.242313

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "80d9e44bc257"
down_revision: Union[str, Sequence[str], None] = "ce85248a2853"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("Principal", "role", existing_type=mysql.VARCHAR(length=32), nullable=True)
    op.alter_column("User", "role", existing_type=mysql.VARCHAR(length=32), nullable=True)

    op.execute("UPDATE User SET role = 'USER' WHERE TRIM(role) = '';")
    op.execute("UPDATE Principal SET role = 'USER' WHERE TRIM(role) = '';")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("User", "role", existing_type=mysql.VARCHAR(length=32), nullable=False)
    op.alter_column("Principal", "role", existing_type=mysql.VARCHAR(length=32), nullable=False)
    # ### end Alembic commands ###
