"""add Role

Revision ID: d836f73ac424
Revises: 0b13c19e2a3d
Create Date: 2026-03-10 21:35:35.186931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd836f73ac424'
down_revision: Union[str, Sequence[str], None] = '0b13c19e2a3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Principal', sa.Column('role', sa.String(length=32), nullable=False))
    op.add_column('User', sa.Column('role', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'role')
    op.drop_column('Principal', 'role')
    # ### end Alembic commands ###
